@weroApi = {{protocol}}://{{hostname}}:{{port}}/api

@raceId = 63e5bd05560948581ee44a14
GET {{weroApi}}/race.get?id={{raceId}}

###

GET {{weroApi}}/race.find

###

@raceName = Gfny
@raceCity = Villavicencio
GET {{weroApi}}/race.find
    ?name={{raceName}}
    &city={{raceCity}}

###

POST {{weroApi}}/race.create
Content-Type: application/json

{
    "name": "test",
    "distance": 1.2,
    "discipline": "Road",
    "date": "2023-12-16 16:40:36Z",
    "location": {
        "address": "Centro",
        "city": "Sopo",
        "region": "Cundinamarca",
        "country": "Colombia"
    },
    "image": "empty.png"
}