@weroApi = {{protocol}}://{{hostname}}:{{port}}/api

@raceId = 63e92867d5bbd2fef288ebb5
GET {{weroApi}}/race.get?id={{raceId}}

###

GET {{weroApi}}/race.find

###

@raceName = Gfny
@raceCity = Villavicencio
GET {{weroApi}}/race.find
    ?name={{raceName}}
    &city={{raceCity}}

###

POST {{weroApi}}/ride.create
Content-Type: application/json

{
    "name": "test",
    "description": "Nice race to have fun",
    "startAt": "2023-12-16 16:40:36Z",
    "route": {
        "distance": 1.2,
        "elevation": 1200,
        "profile": "flat",
        "description": "Small hills of 100m or 200m"
    },
    "discipline": "Road",
    "location": {
        "address": "Centro",
        "city": "Sopo",
        "region": "Cundinamarca",
        "country": "Colombia"
    },
    "image": "empty.png"
}
