@weroApi = {{protocol}}://{{hostname}}:{{port}}/api

@rideId = 6415900fe6b67acb8f756d15
GET {{weroApi}}/ride.get?id={{rideId}}

###

POST {{weroApi}}/ride.find
Content-Type: application/json

{
  "query": {
    "country": "Colombia"
  },
  "size": 3,
  "page": 0
}

###

@rideName = My Race
@rideCity = Sopo
POST {{weroApi}}/ride.find
Content-Type: application/json

{
  "query": {
    "name": "{{rideName}}",
    "city": "{{rideCity}}"
  }
}

###

POST {{weroApi}}/ride.find
Content-Type: application/json

{
  "size": 2,
  "page": 1
}

###

POST {{weroApi}}/ride.find
Content-Type: application/json

{
}

###

@RaceCode = 05
POST {{weroApi}}/ride.create
Content-Type: application/json

{
    "name": "Race {{RaceCode}}",
    "description": "Race {{RaceCode}}",
    "startAt": "2023-12-16 16:40:36Z",
    "route": {
        "distance": 1.2,
        "elevation": 1200,
        "profile": "flat",
        "description": "Small hills of 100m or 200m"
    },
    "discipline": "Road",
    "category": "Race",
    "location": {
        "address": "Centro",
        "city": "Sopo",
        "region": "Cundinamarca",
        "country": "Colombia"
    },
    "website": "https://grocer.nz"
}

###

POST {{weroApi}}/ride.create
Content-Type: application/json

{
    "name": "Shimano Gravel Grind - Lake Taupo - Cycle Challenge",
    "description": "Be a part of the growing gravel riding community in the epic, new Shimano Gravel Grind event. This 75km adventure event combines sealed and unsealed surfaces and showcases some of the unique points of difference and scenery that the Taupō district has to offer.",
    "startAt": "2023-11-24 19:15:00Z",
    "route": {
        "distance": 75,
        "elevation": 860,
        "profile": "Rolling",
        "description": "Using local MTB tracks, gravel roads, farm tracks, and tar-sealed roads in the region, this event is all about the experience, but it also features a timed hill climb and sprint stage for those with a competitive spirit. As the course takes place on some private roads please do not ride on these at any time except on the event. The course is approximately 23% Tarseal, 56% Gravel roads, 16% Mountain Bike trails and 5% other. The Mountain Bike trails are mostly Grade 2 or very easy Grade 3."
    },
    "discipline": "Gravel",
    "format": "Race",
    "location": {
        "address": "Redoubt Street, Taupō 3330",
        "city": "Taupo",
        "region": "Waikato",
        "country": "New Zealand"
    },
    "website": "https://www.cyclechallenge.com/shimano-gravel-grind"
}
