@weroApi = {{protocol}}://{{hostname}}:{{port}}/api

@rideId = 6415900fe6b67acb8f756d15
GET {{weroApi}}/ride.get?id={{rideId}}

###

POST {{weroApi}}/ride.find
Content-Type: application/json

{
  "query": {
    "country": "Colombia"
  },
  "size": 3,
  "page": 0
}

###

@rideName = My Race
@rideCity = Sopo
POST {{weroApi}}/ride.find
Content-Type: application/json

{
  "query": {
    "name": "{{rideName}}",
    "city": "{{rideCity}}"
  }
}

###

POST {{weroApi}}/ride.find
Content-Type: application/json

{
  "size": 2,
  "page": 1
}

###

POST {{weroApi}}/ride.find
Content-Type: application/json

{
}

###

@RaceCode = 05
POST {{weroApi}}/ride.create
Content-Type: application/json

{
    "name": "Race {{RaceCode}}",
    "description": "Race {{RaceCode}}",
    "startAt": "2023-12-16 16:40:36Z",
    "route": {
        "distance": 1.2,
        "elevation": 1200,
        "profile": "flat",
        "description": "Small hills of 100m or 200m"
    },
    "discipline": "Road",
    "category": "Race",
    "location": {
        "address": "Centro",
        "city": "Sopo",
        "region": "Cundinamarca",
        "country": "Colombia"
    },
    "website": "https://grocer.nz"
}

###

POST {{weroApi}}/ride.create
Content-Type: application/json

{
    "name": "Enduro - Lake Taupo - Cycle Challenge",
    "description": "Enduro by name, enduro by nature. The Enduro uses the same course as the cornerstone event of the Lake Taupo Cycle Challenge, Round the Lake, TWICE!",
    "startAt": "2023-11-24 13:30:00Z",
    "route": {
        "distance": 322,
        "elevation": 1650,
        "profile": "Rolling",
        "description": "The Enduro event complete two full laps of the lake which is approximately 322km using the Poihipi/Marotiri loop. Last year the winning male time was 9 hours 33 minutes. The winning female time was 10 hours 11 minutes.",
        "depart_at": {
          "address": "Redoubt Street, Taupō 3330",
          "city": "Taupo",
          "region": "Waikato",
          "country": "New Zealand"
        }
    },
    "discipline": "Road",
    "format": "Race",
    "contact": {
      "website": "https://www.cyclechallenge.com/enduro"
    }
}
