[server]
port = "7878"
env = "Dev"

[log]
level = "info"

[db]
connection_string = "mongodb+srv://fredyd:temp1234@cluster0.ilsnrak.mongodb.net/?retryWrites=true&w=majority"
db_name = "werodb"
races_collection = "races"