name: checkPr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: checkPr
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: cargo build --verbose

      - name: runTests
        run: cargo test --verbose
