name: checkPr

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: checkPr
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: installCargoAudit
        run: cargo install cargo-audit

      - name: build
        run: cargo build

      - name: runTests
        run: cargo test

      - name: clippy
        run: cargo clippy -- -D warnings

      - name: audit
        run: cargo audit --ignore=RUSTSEC-2020-0071
