name: dev
concurrency: dev
run-name: ${{ github.actor }} run this workflow
on:
  push:
    branches:
      - dev

env:
  ENV_NAME: dev
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_NAME: ${{ github.repository }}
  APP_NAME: devwero
  SLOT_NAME: production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ env.ENV_NAME }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: buildAndPush
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ env.ENV_NAME }}
    steps:
      - name: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref }}
