name: restoreBranches
concurrency: ${{ github.repository }}
run-name: ${{ github.actor }} run this workflow

on:
  workflow_dispatch:
    inputs:
      branches:
        description: A comma-delimited list of branches
        default: dev

jobs:
  restore:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkoutCode
        uses: actions/checkout@v3

      - name: restore
        shell: bash
        run: |
          git fetch
          for branch in $( echo ${{ inputs.branches }} | sed 's/ //g' | sed 's/,/ /g' )
          do
            echo "Restoring $branch branch"
            git checkout $branch
            git reset --hard origin/main
            git push -f
          done
